# a build with no CI
trigger: none
  
jobs:
- job: Deploy_Infrastructure_via_Terraform
  pool:
    name: Hosted VS2017

  steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in override.tf'
    inputs:
      rootDirectory: Terraform/ContosoTravel
      targetFiles: override.tf
  
  - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
    displayName: 'Terraform init'
    inputs:
      InstallTerraform: true
      TemplatePath: Terraform/ContosoTravel
      Arguments: init
      UseAzureSub: true
      ConnectedServiceNameARM: $(ConnectedServiceName)
  
  - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
    displayName: 'Terraform plan'
    inputs:
      InstallTerraform: true
      TemplatePath: Terraform/ContosoTravel
      Arguments: 'init -var "location=$(location)" -var "namePrefix=$(namePrefix)"'
      UseAzureSub: true
      ConnectedServiceNameARM: $(ConnectedServiceName)
  
  - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
    displayName: 'Terraform apply'
    inputs:
      InstallTerraform: true
      TemplatePath: Terraform/ContosoTravel
      Arguments: 'apply -var "location=$(location)" -var "namePrefix=$(namePrefix)" -var "cdn=$(cdn)" -var "trafficmanager=$(trafficmanager)" -var "apimgmt=$(apimgmt)" -var "firewall=$(firewall)" -var "appgateway=$(appgateway)" -var "mobile=$(mobile)" -var "adb2c=$(adb2c)" -var "streamanalytics=$(streamanalytics)" -var "cognitiveservices=$(cognitiveservices)" -var "sqldatawarehouse=$(sqldatawarehouse)" -var "hdinsight=$(hdinsight)" -var "search=$(search)" -var "bot=$(bot)" -var "servicePrincipalObjectId=$(servicePrincipalObjectId)" -var "resourceGroupName=$(ResourceGroupName)" -var "servicePrincipalClientId=$(servicePrincipalClientId)" -var "servicePrincipalSecretName=$(servicePrincipalSecretName)" -var "backend=$(backend)" -var "web=$(web)" -auto-approve'
      UseAzureSub: true
      ConnectedServiceNameARM: $(ConnectedServiceName)
