# a build with no CI
trigger: none
  
jobs:
- job: Deploy_Infrastructure_via_Terraform
  pool:
    name: Hosted VS2017

  steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in override.tf'
    inputs:
      rootDirectory: Terraform/ContosoTravel
      targetFiles: override.tf

  - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
    displayName: 'Terraform init'
    inputs:
      InstallTerraform: true
      TemplatePath: Terraform/ContosoTravel
      Arguments: 'init'
      UseAzureSub: true
      ConnectedServiceNameARM: $(ConnectedServiceName)
  
  - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
    displayName: 'Terraform plan'
    inputs:
      InstallTerraform: true
      TemplatePath: Terraform/ContosoTravel
      Arguments: 'plan'
      UseAzureSub: true
      ConnectedServiceNameARM: $(ConnectedServiceName)
  
  - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
    displayName: 'Terraform apply'
    inputs:
      InstallTerraform: true
      TemplatePath: Terraform/ContosoTravel
      Arguments: 'apply -auto-approve'
      UseAzureSub: true
      ConnectedServiceNameARM: $(ConnectedServiceName)
