# a build with no CI
trigger: none
  
jobs:
- job: Deploy_LoadTest_via_Terraform
  pool:
    name: Hosted Ubuntu 1604

  variables:
    ConnectedServiceName_local: $(ConnectedServiceName)

  steps:
  - task: AzureCLI@1
    displayName: 'Azure CLI - Run Terraform'
    inputs:
      addSpnToEnvironment: true    
      azureSubscription: '${{ variables.ConnectedServiceName_local }}'
      scriptPath: '$(Build.sourcesDirectory)/Terraform/ContosoTravel/LoadTest/deploy.bash'
      arguments: '$(namePrefix) $(ResourceGroupName)'
      workingDirectory: $(Build.sourcesDirectory)
